language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install coverage
  - pip install -r requirements.txt
script: coverage run --source=content_gallery runtests.py
after_success:
  - pip install coveralls
  - coveralls
