language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.10.7
  - DJANGO_VERSION=1.11.2
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements_test.txt
script: coverage run --source=content_gallery runtests.py
after_success:
  - pip install coveralls
  - coveralls
