from django.conf import settings

try:
    GALLERY_IMAGE_WIDTH = settings.GALLERY_IMAGE_WIDTH
    GALLERY_IMAGE_HEIGHT = settings.GALLERY_IMAGE_HEIGHT
except AttributeError:
    GALLERY_IMAGE_WIDTH = 600
    GALLERY_IMAGE_HEIGHT = 450

try:
    GALLERY_THUMBNAIL_WIDTH = settings.GALLERY_THUMBNAIL_WIDTH
    GALLERY_THUMBNAIL_HEIGHT = settings.GALLERY_THUMBNAIL_HEIGHT
except AttributeError:
    GALLERY_THUMBNAIL_WIDTH = 133
    GALLERY_THUMBNAIL_HEIGHT = 100
