# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_gallery', '0003_auto_20170305_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
