# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_gallery', '0004_auto_20170309_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='src',
            new_name='image',
        ),
    ]
