# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 18:45
from __future__ import unicode_literals

import content_gallery.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_gallery', '0006_auto_20170504_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=content_gallery.fields.GalleryImageField(upload_to='content_gallery'),
        ),
    ]
